## NumPy Exercises

Importing NumPy and printing version number

In [9]:
import numpy as np

In [10]:
numpy.version.version

'1.21.2'

### EXERCISE 1 - Element-wise addition of 2 numpy arrays
Create 2 two-dimensional numpy arrays, get a numpy array output in which every element is an elment-wise sum of the 2 numpy arrays created.

In [16]:
ex1ar1 = np.array([[1, 2, 3], [4, 5, 6]])
ex1ar2 = np.array([[7, 8, 9], [10, 11, 12]])

sum = ar1 + ar2
sum

array([[ 8, 10, 12],
       [14, 16, 18]])

### EXERCISE 2 - Multiplying a matrix (numpy array) by a scalar
Create a numpy array (matrix), then get a numpy array output which is equal to the original matrix multiplied by a scalar

In [18]:
ex2 = np.array([150, 200, 250, 300])
ex2 *= 3
ex2

array([450, 600, 750, 900])

### EXERCISE 3 - Identity Matrix
Create an identity matrix of dimension 4-by-4

In [19]:
ex3 = np.identity(4)
ex3

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### EXERCISE 4 - Array re-dimensioning
Convert a 1-D array to a 3-D array

In [21]:
ex4 = np.array([1, 2, 3])
np.resize(ex4, (3, 3, 3))

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

### EXERCISE 5 - Horizontal Stacking of Numpy Arrays
Stack 2 numpy arrays horizontally i.e., 2 arrays having the same 1st dimension (number of rows in 2D arrays) using numpy.concatenate()

In [26]:
ex5ar1 = np.array([[1, 2, 3], [4, 5, 6]])
ex5ar2 = np.array([[1, 2, 3], [4, 5, 6]])

np.hstack((ex5ar1, ex5ar2))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

### EXERCISE 6 - Vertically Stacking of Numpy Arrays
Stack 2 numpy arrays vertically i.e., 2 arrays having the same last dimension (number of columns in 2D arrays) using numpy.concatenate()

In [27]:
np.vstack((ex5ar1, ex5ar2))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

### EXERCISE 7 - Custom Sequence Generation
Generate a sequence of numbers in the form of a numpy array from 0 to 100 with gaps of 2 numbers, for example: 0, 2, 4 ....

In [31]:
ex7 = np.arange(0, 100, 2)
ex7

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

### EXERCISE 8 - Generation of given count of equally spaced numbers within a specified range
Output a sequence of equally gapped 5 numbers in the range 0 to 100 (both inclusive) <br>
hint: use `linspace`

In [33]:
#By equally gapped 5 numbers, I assume it wants five numbers evenly spaced from 1-100. Wording is a bit unclear.
ex8 = np.linspace(0, 100, num = 5, endpoint = True)
ex8

array([  0.,  25.,  50.,  75., 100.])

### EXERCISE 9 - Array Generation of random integers within a specified range

Output a 5-by-5 array of random integers between 0 (inclusive) and 10 (exclusive)

In [39]:
ex9 = np.random.randint(0, 10, size = (5, 5))
ex9

array([[8, 7, 6, 7, 6],
       [6, 0, 7, 9, 1],
       [7, 8, 1, 7, 2],
       [7, 7, 6, 0, 8],
       [5, 6, 3, 4, 9]])

### EXERCISE 10 - Matrix Multiplication

Given 2 numpy arrays as matrices, output the result of multiplying the 2 matrices (as a numpy array)

In [42]:
ex10ar1 = np.array([[1, 2, 3], [4, 5, 6]])
ex10ar2 = np.array([[7, 8, 9], [10, 11, 12]])

ex10mult = ex10ar1 * ex10ar2
ex10mult

array([[ 7, 16, 27],
       [40, 55, 72]])